name: Deploy portfolio

on:
  push:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read

env:
  STACK_NAME: portfolio-template
  REGION: us-east-1
  DOMAIN: portfolio.cal-overflow.dev
  NUXT_ENV_SITE_URL: https://portfolio.cal-overflow.dev # This value does not matter here
  NUXT_ENV_FULL_NAME: Example Portfolio
  NUXT_ENV_EMAIL_ADDRESS: cal-overflow@users.noreply.github.com

jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies 👨🏻‍💻
        run: npm ci --prefer-offline --no-audit

      - name: Run unit tests 🧪
        run: npm run unit

  deploy:
    needs: acceptance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: ${{ env.REGION }}

      - name: Deploy stack
        run: |
          sam deploy --stack-name $STACK_NAME --region $REGION --parameter-overrides "Domain=$DOMAIN"

      - name: Build and deploy static site
        run: |
          mkdir example_content
          git clone https://github.com/cal-overflow/example-portfolio-content.git example_content
          cp -r example_content/content/* src/content
          cp -r example_content/assets/* src/assets

          npm ci
          npm run generate

          BUCKET=$(aws cloudformation describe-stacks --stack-name=$STACK_NAME --region $REGION --query 'Stacks[0].Outputs[?OutputKey==`S3BucketName`].OutputValue' --output text)
          aws s3 sync dist s3://$BUCKET

  run_e2e_tests:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies 👨🏻‍💻
        run: npm ci --prefer-offline --no-audit

      - name: Run e2e tests 🤖
        run: |
          export CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_baseUrl=$NUXT_ENV_SITE_URL npm run e2e:headless:record
